// Generated by IBatisNetModel
	
using System;
using System.Collections.Generic;
using GModel.RoleRight;

namespace GInterfaceDAL.RoleRight
{
    public interface IMenuViewDao
    {
        MenuView GetMenuView(object userinfoId);
        IList<MenuView> GetMenuViewPage(object o);
        IList<MenuPower> GetMenuPower(object o);
        int GetMenuViewCount(object o);
    }
}	
	
	