// Generated by IBatisNetModel
	
using System;
using System.Collections.Generic;
using GModel.RoleRight;

namespace GInterfaceDAL.RoleRight
{
    public interface INotselMenuViewDao
    {
        NotselMenuView GetNotselMenuView(object userinfoId);
        IList<NotselMenuView> GetNotselMenuViewPage(object o);
        int GetNotselMenuViewCount(object o);
    }
}	
	
	