// Generated by IBatisNetModel
	
using System;
using System.Collections.Generic;
using GModel.RoleRight;
using GModel.Basic;

namespace GInterfaceDAL.RoleRight
{
    public interface IRoleInfoDao
    {
        //IList<RoleInfo> GetRoleInfoList(object o);
        int Update(RoleInfo entity);
        int Delete(object condition);
        object Insert(RoleInfo entity);

        RoleInfo GetRoleInfo(object userinfoId);

        IList<RoleView> GetRoleInfoPage(object o);
        IList<RoleView> GetRoleInfoDownList(string o);
        int GetRoleInfoCount(RoleView o);
        RoleInfo GetRoleObjByRoleId(string RoleId);
    }
}	
	
	