// Generated by IBatisNetModel
	
using System;
using System.Collections.Generic;
using GModel.RoleRight;

namespace GInterfaceDAL.RoleRight
{
    public interface ISelMenuViewDao
    {
        SelMenuView GetSelMenuView(object userinfoId);
        IList<SelMenuView> GetSelMenuViewPage(object o);
        int GetSelMenuViewCount(object o);
    }
}	
	
	