// Generated by IBatisNetModel
	
using System;
using System.Collections.Generic;
using GModel.InterFace;

namespace GInterfaceDAL.InterFace
{
    public interface IOldterPostbacktimesDao
    {
        //IList<OldterPostbacktimes> GetOldterPostbacktimesList(object o);
        int Update(OldterPostbacktimes entity);
        int Delete(object condition);
        object Insert(OldterPostbacktimes entity);

        int GetOldterPostbacktimes(string TerNo,ref string msg);

        IList<OldterPostbacktimes> GetOldterPostbacktimesPage(object o );
        int GetOldterPostbacktimesCount(object o);
    }
}	
	
	