// Generated by IBatisNetModel
	
using System;
using System.Collections.Generic;
using GModel.InterFace;

namespace GInterfaceDAL.InterFace
{
    public interface IRawDataDao
    {
        //IList<RawData> GetRawDataList(object o);
        //int Update(RawData entity);
        //int Delete(object condition);
        object Insert(RawData entity);

        //RawData GetRawData(object userinfoId);

        //IList<RawData> GetRawDataPage(object o);
        //int GetRawDataCount(object o);
    }
}	
	
	