// Generated by IBatisNetModel
	
using System;
using System.Collections.Generic;
using GModel.InterFace;

namespace GInterfaceDAL.InterFace
{
    public interface ISendinfoLastDao
    {
        //IList<SendinfoLast> GetSendinfoLastList(object o);
        int Delete(object condition);
        object Insert(SendinfoLast entity);

        SendinfoLast GetSendinfoLast(SendinfoLast SFL);
        SendinfoLast GetSendinfoLastByOldId(string oldid);

        IList<SendinfoLast> GetSendinfoLastPage(object o);
        int GetSendinfoLastCount(object o);

       string UpdateStatus(string id,double sendid, string sendcmd, string status);

       string UpdateStatusNew(string oldidid, double sendid, string sendcmd, string status);

       string UpdateSendInfo(string id, string sendcmd, string status,double sendId);
       string UpdateSendInfoByOldid(string oldid,string resultStr,string status,double SendinfoId);
       string UpdateSendInfoFail(string id,string status,string resultStr,double sendId);
       string UpdateSendInfoFailByOldId(string oldid, string status, string resultStr, double sendId);
       SendinfoLast GetCmd(string DeviceId);
       IList<SendinfoLast> GetSendinfoLastPageByTerNos(SendinfoLast s);
       int GetSendinfoLastCountByTerNos(SendinfoLast s);

    }
}	
	
	