// Generated by IBatisNetModel
	
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using IBatisNet.Common.Pagination;
using GModel.InterFace;
using System.Collections;

namespace GInterfaceDAL.InterFace
{
    public interface ISendinfoyxLastDao
    {
        IList<SendinfoyxLast> GetSendinfoLastPage(Hashtable ht);
        string SetSendStatus(Hashtable ht);
    }
}	
	
	