// Generated by IBatisNetModel

using System;
using IBatisNet.Common.Pagination;
using GModel.InterFace;
using GInterfaceDAL.InterFace;
using System.Data;
using GDAL.InterFace;
using GBLL.InterFace;
using System.Collections;

namespace GBLL.InterFace
{
    public class SendinfoyxLastBLL
    {
        private ISendinfoyxLastDao _iSendinfoyxLastDao = null;

        public SendinfoyxLastBLL()
        {
            _iSendinfoyxLastDao = new SendinfoyxLastDao();

        }

        public System.Collections.Generic.IList<SendinfoyxLast> GetSendinfoyxLastPageByTerNo(string TerNo, int rows, int page) 
        {
            Hashtable ht = new Hashtable();
            ht.Add("DeviceId", TerNo);

            if (!ht.ContainsKey("EndData"))
            {
                ht.Add("EndData", 0);
            }
            if (!ht.ContainsKey("StartData"))
            {
                ht.Add("StartData", 0);
            }
           return _iSendinfoyxLastDao.GetSendinfoLastPage(ht);
            
        }

        public string GetSendPageByTerNoAndCommand(string TerNo,string Command, int rows, int page) 
        {
            Hashtable ht = new Hashtable();
            ht.Add("DeviceId", TerNo);
            ht.Add("SendinfoCommand", Command);
            if (!ht.ContainsKey("EndData"))
            {
                ht.Add("EndData", 0);
            }
            if (!ht.ContainsKey("StartData"))
            {
                ht.Add("StartData", 0);
            }
           return _iSendinfoyxLastDao.SetSendStatus(ht);
            
        }

        


       
    }
}
	