// Generated by IBatisNetModel

using System;
using System.Collections;

using IBatisNet.Common.Pagination;

using GModel.InterFace;
using GInterfaceDAL.InterFace;
using System.Data;
using GDAL.InterFace;
using System.Collections.Generic;

namespace GBLL.InterFace
{
    public class SendinfoyxBLL
    {

        private ISendinfoyxDao _iSendinfoyxDao = null;

        public  SendinfoyxBLL()
        {
            _iSendinfoyxDao = new SendinfoyxDao();
        }
        /// <summary>
        /// 同时插入SendInfoyx和SendInfoyxLast表
        /// </summary>
        /// <param name="entity"></param>
        /// <returns>失败时返回设备ID</returns>
        public string InsertData(Sendinfoyx entity)
        {
            try
            {
                entity.SendinfoStatus = 0;
                return _iSendinfoyxDao.InsertData(entity);
            }
            catch (Exception e)
            {
                return entity.DeviceId;
            }
        }

        public IList<Sendinfoyx> GetSendinfoListByTerNo(object o)
        {
            return _iSendinfoyxDao.SelectSendinfoListByTerNo(o);

        }


        public int GetSendinfoCountByTerNo(object o)
        {
            return _iSendinfoyxDao.GetSendinfoCountByTerNo(o);
        }
    }
}
	