// Generated by IBatisNetModel

using System;
using System.Collections;

using GModel.InterFace;
using GInterfaceDAL.InterFace;
using GDAL.InterFace;
using System.Collections.Generic;

namespace GBLL.InterFace
{
    public class SendinfoLastBLL
    {
        private ISendinfoLastDao _iSendinfoLastDao = null;
        private ISendinfoDao _iSendinfoDao = null;
        public SendinfoLastBLL()
        {
            _iSendinfoLastDao = new SendinfoLastDao();
            _iSendinfoDao = new SendinfoDao();
        }

        /// <summary>
        /// 查询发送命令，待发送命令
        /// </summary>
        /// <param name="o"></param>
        /// <returns></returns>
        public SendinfoLast GetCmd(string o)
        {
            //return _iSendinfoLastDao.GetSendinfoLast(o);
            return _iSendinfoLastDao.GetCmd(o);
        }

        //public IList<SendinfoLast> GetSendinfoLastPage(object o)
        //{
        //    return _iSendinfoLastDao.GetSendinfoLastPage(o);
        //}

        //public int GetSendinfoLastCount(object o)
        //{
        //    return _iSendinfoLastDao.GetSendinfoLastCount(o);
        //}

        /// <summary>
        /// 根据终端编号查询待发送命令
        /// </summary>
        /// <param name="o"></param>
        /// <returns></returns>
        public IList<SendinfoLast> GetSendinfoLastPageByTerNos(SendinfoLast o)
        {
            return _iSendinfoLastDao.GetSendinfoLastPageByTerNos(o);
        }

        public int GetSendinfoLastCountByTerNos(SendinfoLast o) 
        {
            return _iSendinfoLastDao.GetSendinfoLastCountByTerNos(o);
           
        
        }


        public string Insert(SendinfoLast entity)
        {
            try
            { 
                object o = _iSendinfoLastDao.Insert(entity);
                if (o == null)
                {
                    return "true";
                }
                else 
                {
                    return "false";
                }

            }
            catch (Exception e)
            {

                return e.Message;
            }
           
        }

        //public int Update(SendinfoLast entity)
        //{
        //    return _iSendinfoLastDao.Update(entity);
        //}

        //public int Delete(string condition)
        //{
        //    return _iSendinfoLastDao.Delete(condition);
        //}



        /// <summary>
        /// 发送命令后、命令执行成功后、命令执行失败等更新状态
        /// </summary>
        /// <param name="id"></param>
        /// <param name="sendcmd"></param>
        /// <param name="status"></param>
        /// <returns></returns>
        public string UpdateStatus(string id, string sendcmd, string status)
        {
            try
            {
                SendinfoLast SFSel = new SendinfoLast();
                SFSel.Id = Convert.ToDouble(id);
                SendinfoLast si = _iSendinfoLastDao.GetSendinfoLast(SFSel);
                if (si != null)
                {
                    return _iSendinfoLastDao.UpdateStatus(id,si.SendinfoId, sendcmd, status);
                }
                else
                {
                    return "false";
                }
            }
            catch (Exception e)
            {
                return "false";
            }
        }

        /// <summary>
        /// 发送命令后、命令执行成功后、命令执行失败等更新状态
        /// </summary>
        /// <param name="id"></param>
        /// <param name="sendcmd"></param>
        /// <param name="status"></param>
        /// <returns></returns>
        public string UpdateStatusNew(string oldid, string sendcmd, string status)
        {
            try
            {
                //SendinfoLast SFSel = new SendinfoLast();
                //SFSel.OldId = Convert.ToDouble(oldid);
                SendinfoLast si = _iSendinfoLastDao.GetSendinfoLastByOldId(oldid);
                if (si != null)
                {
                    return _iSendinfoLastDao.UpdateStatusNew(oldid, si.SendinfoId, sendcmd, status);
                }
                else
                {
                    return "false";
                }
            }
            catch (Exception e)
            {
                return "false";
            }
        }





        /// <summary>
        /// 命令回执后执行成功的命令处理。更新发送命令历史表，删除待发送命令表记录
        /// </summary>
        /// <param name="id"></param>
        /// <param name="status"></param>
        /// <param name="resultStr"></param>
        /// <returns></returns>
        public string UpdateSendInfo(string id, string status, string resultStr)
        {
            try
            {
                SendinfoLast SFL = new SendinfoLast();
                SFL.Id = Convert.ToDouble(id);
                SendinfoLast si = _iSendinfoLastDao.GetSendinfoLast(SFL);
                if (si != null)
                {
                    return _iSendinfoLastDao.UpdateSendInfo(id, resultStr, status, si.SendinfoId);
                }
                else
                {
                    return "false";
                }
            }
            catch (Exception e)
            {
                return "false";
            }
        }

        /// <summary>
        /// 命令回执后执行成功的命令处理。更新发送命令历史表，删除待发送命令表记录
        /// </summary>
        /// <param name="id"></param>
        /// <param name="status"></param>
        /// <param name="resultStr"></param>
        /// <returns></returns>
        public string UpdateSendInfoByOldId(string oldid, string status, string resultStr)
        {
            try
            {
                //SendinfoLast SFL = new SendinfoLast();
                //SFL.Id = Convert.ToDouble(oldid);
                SendinfoLast si = _iSendinfoLastDao.GetSendinfoLastByOldId(oldid);
                //SendinfoLast si = _iSendinfoLastDao.GetSendinfoLast(SFL);
                if (si != null)
                {
                    return _iSendinfoLastDao.UpdateSendInfoByOldid(oldid, resultStr, status, si.SendinfoId);
                }
                else
                {
                    return "false";
                }
            }
            catch (Exception e)
            {
                return "false";
            }
        }

        /// <summary>
        /// 命令发送失败处理
        /// </summary>
        /// <param name="id"></param>
        /// <param name="status"></param>
        /// <param name="resultStr"></param>
        /// <returns></returns>
        public string UpdateSendInfoFail(string id, string status, string resultStr)
        {
            try
            {
                SendinfoLast SFL = new SendinfoLast();
                SFL.Id = Convert.ToDouble(id);
                SendinfoLast si = _iSendinfoLastDao.GetSendinfoLast(SFL);
                if (si != null)
                {
                    return _iSendinfoLastDao.UpdateSendInfoFail(id, status, resultStr, si.SendinfoId);
                }
                else 
                {
                    return "false";
                }
            }
            catch (Exception)
            {
                return "false";           
            }        
        }

        /// <summary>
        /// 命令发送失败处理
        /// </summary>
        /// <param name="oldid"></param>
        /// <param name="status"></param>
        /// <param name="resultStr"></param>
        /// <returns></returns>
        public string UpdateSendInfoFailByOldId(string oldid, string status, string resultStr)
        {
            try
            {
                //SendinfoLast SFL = new SendinfoLast();
                //SFL.OldId = Convert.ToDouble(oldid);
                SendinfoLast si = _iSendinfoLastDao.GetSendinfoLastByOldId(oldid);
                //SendinfoLast si = _iSendinfoLastDao.GetSendinfoLast(SFL);
                if (si != null)
                {
                    return _iSendinfoLastDao.UpdateSendInfoFailByOldId(oldid, status, resultStr, si.SendinfoId);
                }
                else
                {
                    return "false";
                }
            }
            catch (Exception)
            {
                return "false";
            }
        }
    }
}
