// Generated by IBatisNetModel

using System;
using System.Collections;

using GDAL.Basic;
using GModel.Basic;
using GInterfaceDAL.Basic;
using System.Collections.Generic;

namespace GBLL.Basic
{
    public class DeptInfoBLL
    {
        private IDeptInfoDao _iDeptInfoDao = null;
        public DeptInfoBLL()
        {
            _iDeptInfoDao = new DeptInfoDao();
        }

        public DeptInfo GetDeptInfo(string DeptId)
        {
            return _iDeptInfoDao.GetDeptInfoById(DeptId);
        }

        public DeptInfo GetDeptInfoByCode(string DeptCode)
        {
            return _iDeptInfoDao.GetDeptInfoByCode(DeptCode);
        }

        public IList<DeptInfo> GetDeptInfoPage(object o)
        {
            return _iDeptInfoDao.GetDeptInfoPage(o);
        }

        public int GetDeptInfoCount(object o)
        {
            return _iDeptInfoDao.GetDeptInfoCount(o);
        }

        //public IList<DeptInfo> GetDeptInfoList(object o)
        //{
        //return _iDeptInfoDao.GetDeptInfoList(o);
        //}

        public int GetDeptCountByFatherId(string DeptId)
        {
            return _iDeptInfoDao.GetDeptCountByFatherId(DeptId);
        }

        public object Insert(DeptInfo entity)
        {
            if (entity.Businessdivisionname == null 
                || entity.Businessdivisionname.Trim() == "")
            {
                return "企业名称不能为空！";
            }
            else if (entity.Fatherid == null 
                || entity.Fatherid.Trim() == "")
            {
                return "父企业不能为空！";
            }
            else 
            { 
                return _iDeptInfoDao.Insert(entity);
            }
        }

        public int Update(DeptInfo entity, List<string> OldDeptCode, List<string> NewDeptCode)
        {
            return _iDeptInfoDao.Update(entity, OldDeptCode, NewDeptCode);
        }

        /// <summary>
        /// 假删除
        /// </summary>
        /// <param name="Businessdivisionid"></param>
        /// <returns></returns>
        public int Delete(string Businessdivisionid)
        {
            if (Businessdivisionid == null || Businessdivisionid.Trim() == "")
            {
                return -4;
            }
            else
            {
                return _iDeptInfoDao.Delete(Businessdivisionid);
            }
        }

        public int DeleteChildren(string Businessdivisionid)
        {
            if (Businessdivisionid == null || Businessdivisionid.Trim() == "") 
            {
                return -4;
            }
            else
            {
                return _iDeptInfoDao.DeleteChildren(Businessdivisionid);
            }           
        }
    }
}
