// Generated by IBatisNetModel

using System;
using System.Collections;

using GModel;
using GModel.Basic;
using GModel.RoleRight;
using GInterfaceDAL.Basic;
using GDAL.Basic;
using GDAL.RoleRight;
using GInterfaceDAL.RoleRight;
using System.Collections.Generic;

namespace GBLL.Basic
{
    public class UserInfoBLL
    {
        private IUserInfoDao _iUserInfoDao = null;
        private IRoleInfoDao _iRoleInfoDao = null;
        public UserInfoBLL()
        {
            _iUserInfoDao = new UserInfoDao();
            _iRoleInfoDao = new RoleInfoDao();
        }

        public UserInfo GetUserInfo(object o)
        {
            return _iUserInfoDao.GetUserInfo(o);
        }

        public UserInfo GetTerUserInfo(object o)
        {
            return _iUserInfoDao.GetTerUserInfo(o);
        }

        public IList<UserInfo> GetUserInfoPage(object o)
        {
            return _iUserInfoDao.GetUserInfoPage(o);
        }

        public int GetUserInfoCount(object o)
        {
            return _iUserInfoDao.GetUserInfoCount(o);
        }

        public int Insert(UserInfo entity)
        {
            return Convert.ToInt32(_iUserInfoDao.Insert(entity));
        }

        public int Update(UserInfo entity)
        {
            return _iUserInfoDao.Update(entity);
        }

        public int Delete(string condition)
        {
            return _iUserInfoDao.Delete(condition);
        }

        public int ResetUser(UserInfo condition)
        {
            return _iUserInfoDao.ResetUser(condition);
        }


        public ResultState UserLogin(UserInfo ui, out UserInfo uiObj)
        {
            ResultState result = ResultState.DEFAULT;
            //LoginUser = userInforManager.GetUserObjByLoginName(UserInfo, out LoginUser);
            uiObj = _iUserInfoDao.GetUserObjByLoginName(ui, out uiObj);
            if (uiObj == null)
            {
                //用户不存在
                result = ResultState.LNAMEERROR;
                return result;
            }
            else if (uiObj.UserPasswrd == ui.UserPasswrd)
            {
                //成功
                return ResultState.SUCCEED;
            }
            else
            {
                //密码错误
                result = ResultState.PWDERROR;
                uiObj = null;
                return result;
            }


            #region
            //else
            //{
            //    if (UserInfo.LOGINNAME == null)
            //    {
            //        result = SysResult.PWDERROR;
            //        uiObj = null;
            //        return result;
            //    }
            //    else if (UserInfo.PWD == uiObj.PWD)//需要加密算法
            //    {
            //        //用户登录成功
            //        //查询用户拥有角色
            //        if (uiObj.ISADMIN == "1")
            //        {
            //            return SysResult.SUCCEED;
            //        }
            //        else if (LoginUser.ISADMIN != "1")//非系统管理员
            //        {
            //            Role roleObj = new Role();
            //            roleObj = userRoleManager.GetRoleObjByUserID(uiObj);
            //            uiObj.RoleObj = roleObj;
            //            switch (roleObj.ROLESTYPE)
            //            {
            //                case "工厂员工":
            //                    Employee EmployeeObj = new Employee();
            //                    EmployeeObj.USERID = LoginUser.USERID;
            //                    LoginUser.EmployeeObj = employeeManager.GetEmployeeObjUserID(EmployeeObj);
            //                    EmployeeObj = LoginUser.EmployeeObj;
            //                    if (EmployeeObj != null)
            //                    {
            //                        return SysResult.SUCCEED;
            //                        break;
            //                    }
            //                    else
            //                    {
            //                        return SysResult.LNAMEERROR;
            //                        break;
            //                    }
            //                    break;
            //                case "经销商":
            //                    AgentUser agentUserObj = new AgentUser();
            //                    agentUserObj.USERID = LoginUser.USERID;
            //                    agentUserObj = agentUserManager.GetAgentUseroObjByUserID(agentUserObj);
            //                    LoginUser.AgentUserObj = agentUserObj;
            //                    if (agentUserObj != null && agentUserObj.DealerObj != null && agentUserObj.DealerObj.STATUS == "0")
            //                    {
            //                        return SysResult.SUCCEED;
            //                        break;
            //                    }
            //                    else
            //                    {
            //                        return SysResult.LNAMEERROR;
            //                        break;
            //                    }

            //                case "市场部":
            //                    BusinessUser businessuser = new BusinessUser();
            //                    businessuser.USERID = LoginUser.USERID;
            //                    businessuser = businessUserManager.GetBuUserObjByUserID(businessuser);
            //                    //STATUS
            //                    if (businessuser != null && businessuser.MarkingObj != null && businessuser.MarkingObj.STATUS == "0")
            //                    {
            //                        LoginUser.BusinessUserObj = businessuser;
            //                        return SysResult.SUCCEED;
            //                    }
            //                    else
            //                    {
            //                        return SysResult.LNAMEERROR;
            //                    }
            //                    break;
            //                case "终端用户":
            //                    ClientUser clientUser = new ClientUser();
            //                    clientUser.USERID = LoginUser.USERID;
            //                    clientUser = clientUserManager.GetBuUserObjByUserID(clientUser);
            //                    if (clientUser != null)
            //                    {
            //                        LoginUser.ClientUserObj = clientUser;
            //                        return SysResult.SUCCEED;
            //                    }
            //                    else
            //                    {
            //                        return SysResult.LNAMEERROR;
            //                    }
            //                    break;
            //            }
            //        }
            //        else
            //        {
            //            return SysResult.ERROR;
            //        }


            //    }
            //    else if (UserInfo.PWD != uiObj.PWD)
            //    {
            //        //密码错误
            //        result = SysResult.PWDERROR;
            //        uiObj = null;
            //        return result;
            //    }
            //}
            #endregion
        }

        public ResultState ModifyUserPWD(UserInfo ui)
        {
            ResultState result = ResultState.DEFAULT;
            int k = _iUserInfoDao.ModifyUserPWD(ui);

            if (k == 1)
            {
                result = ResultState.SUCCEED;
            }
            else
            {
                result = ResultState.ERROR;
            }
            return result;

        }

        public UserInfo GetUserByLName(UserInfo ui, out UserInfo uiObj)
        {
            uiObj = _iUserInfoDao.GetUserObjByLoginName(ui, out uiObj);
            return uiObj;
        }
    }
}
