// Generated by IBatisNetModel

using System;
using System.Collections;

using GModel;
using GModel.Basic;
using GModel.RoleRight;
using GInterfaceDAL.Basic;
using GDAL.Basic;
using GDAL.RoleRight;
using GInterfaceDAL.RoleRight;
using System.Collections.Generic;

namespace GBLL.Basic
{
    public class VersionInfoBLL
    {
        private IVersionInfoDao _iVersionInfoDao = null;

        public VersionInfoBLL()
        {
            _iVersionInfoDao = new VersionInfoDao();
        }

        public IList<VersionInfo> GetVersionViewPage(object o)
        {
            return _iVersionInfoDao.GetVersionViewPage(o);
        }

        public int GetVersionViewCount(object o)
        {
            return _iVersionInfoDao.GetVersionViewCount(o);
        }

        public int Insert(VersionInfo entity)
        {
            return Convert.ToInt32(_iVersionInfoDao.Insert(entity));
        }

        public int Update(VersionInfo entity)
        {
            return _iVersionInfoDao.Update(entity);
        }

        public int Delete(string condition)
        {
            return _iVersionInfoDao.Delete(condition);
        }

        public VersionInfo GetVersionInfo(VersionInfo vi)
        {
            return _iVersionInfoDao.GetVersionInfo(vi); 
        }
    }
}
	