// Generated by IBatisNetModel
using System;

namespace GModel.RoleRight
{
    [Serializable]
    public sealed class RoleView
    {
        #region Private Members
        private bool _isChanged;
        private bool _isDeleted;
        private int _startdata = 0;
        private int _enddata = 0;
        private int _newRow = 0;

        private string _role_id;
        private string _role_name;
        private DateTime _role_date;
        private string _role_remark;
        private string _dept_id;
        private string _businessdivisionname;
        private string _businessdivisioncode;
        #endregion

        #region Default ( Empty ) Class Constuctor
        /// <summary>
        /// default constructor
        /// </summary>
        public RoleView()
        {
            _role_id = "";
            _role_name = "";
            _role_date = new DateTime();
            _role_remark = "";
            _dept_id = "";
            _businessdivisionname = "";
            _businessdivisioncode = "";
        }
        #endregion // End of Default ( Empty ) Class Constuctor

        #region Public Properties

        /// <summary>
        /// 
        /// </summary>		
        public string RoleId
        {
            get { return _role_id; }
            set
            {
                if (value != null && value.Length > 40)
                    throw new ArgumentOutOfRangeException("Invalid value for RoleId", value, value.ToString());

                _isChanged |= (_role_id != value); _role_id = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string RoleName
        {
            get { return _role_name; }
            set
            {
                if (value != null && value.Length > 100)
                    throw new ArgumentOutOfRangeException("Invalid value for RoleName", value, value.ToString());

                _isChanged |= (_role_name != value); _role_name = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public DateTime RoleDate
        {
            get { return _role_date; }
            set { _isChanged |= (_role_date != value); _role_date = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string RoleRemark
        {
            get { return _role_remark; }
            set
            {
                if (value != null && value.Length > 100)
                    throw new ArgumentOutOfRangeException("Invalid value for RoleRemark", value, value.ToString());

                _isChanged |= (_role_remark != value); _role_remark = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string DeptId
        {
            get { return _dept_id; }
            set
            {
                if (value != null && value.Length > 40)
                    throw new ArgumentOutOfRangeException("Invalid value for DeptId", value, value.ToString());

                _isChanged |= (_dept_id != value); _dept_id = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Businessdivisionname
        {
            get { return _businessdivisionname; }
            set
            {
                if (value != null && value.Length > 100)
                    throw new ArgumentOutOfRangeException("Invalid value for Businessdivisionname", value, value.ToString());

                _isChanged |= (_businessdivisionname != value); _businessdivisionname = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Businessdivisioncode
        {
            get { return _businessdivisioncode; }
            set
            {
                if (value != null && value.Length > 80)
                    throw new ArgumentOutOfRangeException("Invalid value for Businessdivisioncode", value, value.ToString());

                _isChanged |= (_businessdivisioncode != value); _businessdivisioncode = value;
            }
        }


        public int StartData
        {
            get { return _startdata; }
            set
            {
                _startdata = value;
            }
        }

        public int EndData
        {
            get { return _enddata; }
            set
            {
                _enddata = value;
            }
        }
        public int NewRow
        {
            get { return _newRow; }
            set { _newRow = value; }
        }
        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public bool IsChanged
        {
            get { return _isChanged; }
        }

        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public bool IsDeleted
        {
            get { return _isDeleted; }
        }

        #endregion


        #region Public Functions

        /// <summary>
        /// mark the item as deleted
        /// </summary>
        public void MarkAsDeleted()
        {
            _isDeleted = true;
            _isChanged = true;
        }

        #endregion


    }
}
