// Generated by IBatisNetModel

using System;
using System.Collections;

using GModel.RoleRight;
using GInterfaceDAL.RoleRight;
using GDAL.RoleRight;
using System.Collections.Generic;

namespace GBLL.RoleRight
{
    public class RoleManuBLL
    {
        private IRoleManuDao _iRoleManuDao = null;
        public RoleManuBLL()
        {
            _iRoleManuDao = new RoleManuDao();
        }

		public RoleManu GetRoleManu(object o)
        {
            return _iRoleManuDao.GetRoleManu( o);
        }

        public IList<RoleManu> GetRoleManuPage(object o)
        {
            return _iRoleManuDao.GetRoleManuPage(o);
        }

		public int GetRoleManuCount(object o)
        {
            return _iRoleManuDao.GetRoleManuCount(o);
        }

        //public IList<RoleManu> GetRoleManuList(object o)
        //{
            //return _iRoleManuDao.GetRoleManuList(o);
        //}

		public int Insert(RoleManu entity)
        {
            return  Convert.ToInt32(_iRoleManuDao.Insert(entity));
        }

        public int Update(RoleManu entity)
        {
            return _iRoleManuDao.Update(entity);
        }
		
        public int Delete(string condition)
        {
            return _iRoleManuDao.Delete(condition);
        }

        public string AddRM(RoleManu rm) 
        {
            string aa = _iRoleManuDao.AddRM(rm);
            return aa;
        
        }

        public int DelRM(RoleManu rm)
        {
           return _iRoleManuDao.DelRM(rm);
            
        
        }
    }
}
	