// Generated by IBatisNetModel

using System;
using System.Collections;

using GModel.RoleRight;
using GInterfaceDAL.RoleRight;
using GDAL.RoleRight;
using System.Collections.Generic;

namespace GBLL.RoleRight
{
    public class RoleInfoBLL
    {
        private IRoleInfoDao _iRoleInfoDao = null;
        public RoleInfoBLL()
        {
            _iRoleInfoDao = new RoleInfoDao();
        }

		public RoleInfo GetRoleInfo(object o)
        {
            return _iRoleInfoDao.GetRoleInfo( o);
        }

        public IList<RoleView> GetRoleInfoPage(object o)
        {
            return _iRoleInfoDao.GetRoleInfoPage(o);
        }

        public IList<RoleView> GetRoleInfoDownList(string DeptId)
        {
            return _iRoleInfoDao.GetRoleInfoDownList(DeptId);
        }

        public int GetRoleInfoCount(RoleView o)
        {
            return _iRoleInfoDao.GetRoleInfoCount(o);
        }

        //public IList<RoleInfo> GetRoleInfoList(object o)
        //{
            //return _iRoleInfoDao.GetRoleInfoList(o);
        //}

		public int Insert(RoleInfo entity)
        {
            return  Convert.ToInt32(_iRoleInfoDao.Insert(entity));
        }

        public int Update(RoleInfo entity)
        {
            return _iRoleInfoDao.Update(entity);
        }
		
        public int Delete(string condition)
        {
            return _iRoleInfoDao.Delete(condition);
        }
    }
}
	