// Generated by IBatisNetModel
	
using System;
using System.Collections.Generic;
using GModel.Car;
using System.Collections;
using GModel.Basic;
using GModel;

namespace GInterfaceDAL.Car
{
    public interface ICarReportDao
    {
        List<TreeMode> GetReportMenuTree();

        List<string> GetTableNames(Hashtable ht);

        List<string> GetTerNos(Hashtable ht);

        //超里程统计
        bool GetVis_Carlist(string userDeptCode);
        System.Data.DataTable GetVis_Carlist_dt(string userDeptCode);

        System.Data.DataTable GetVis_Carlist_dt2(string userDeptCode);
        //里程统计
        #region
        System.Data.DataTable GetCarReport_LCTJViewPage(Hashtable ht);

        #endregion

        //报警统计
        #region

        System.Data.DataTable GetCarReport_BJTJViewPage(Hashtable ht);
        System.Data.DataTable GetCarReport_BJTJViewPage_FY(Hashtable ht);
        int GetCarReport_BJTJViewPage_Count(Hashtable ht);

        #endregion

        //终端统计
        #region

        System.Data.DataTable GetCarReport_ZDTJViewPage(Hashtable ht);
        System.Data.DataTable GetCarReport_ZDTJViewPage_FY(Hashtable ht);
        int GetCarReport_ZDTJViewPage_Count(Hashtable ht);

        #endregion

        IList<CarReport_ZXTJView> GetZxtjViewPage(object o);

        int GetZxtjViewCount(object o);

        IList<CarReport_LXTJView> GetLxtjViewPage(object o);

        IList<CarReport_LCBBView> GetLcbbData(object o);

        IList<CarReport_LCBBView> GetLcbbTodayData(object o);

        int GetLxtjViewCount(object o);

        IList<CarReport_TerData> GetTjbbTerData(Hashtable ht);

        int GetTjbbTerDataCount(Hashtable ht);
    }
}	
	
	