// Generated by IBatisNetModel
	
using System;
using System.Collections.Generic;
using GModel.Car;
using System.Collections;
using GModel.Basic;

namespace GInterfaceDAL.Car
{
    public interface ICarInfoDao
    {
        //IList<CarInfo> GetCarInfoList(object o);
        int Update(CarInfo entity);
        string Delete(object condition,bool RemoveTerno);
        object Insert(CarInfo entity);

        CarInfo GetCarInfoByCarNo(object carno);

        CarInfo GetCarInfoByCarId(object carid);

        IList<CarInfo> GetCarInfoPage(object o);
        int GetCarInfoCount(object o);
        string InsertCarInfo(ArrayList arr);
        string InsertCarInfo(ArrayList arr,string TypeName);
        string UpdateCarInfo(ArrayList arr);
        string UpdateCarInfo(ArrayList arr, string TypeName);
        string UpdateCarType(CarInfo ci, string TypeName);
        string upLoadData(UpLoadTerBind ut, string DeptId);
        CarDetialInfo GetCarDetial(string TerNo); 
    }
}	
	
	