// Generated by IBatisNetModel
	
using System;
using System.Collections.Generic;
using GModel.Car;
using System.Data;
using System.Collections;

namespace GInterfaceDAL.Car
{
    public interface ICarTypeDao
    {
        //IList<CarType> GetCarTypeList(object o);
        int Update(CarType entity);
        string Delete(object condition);
        object Insert(CarType entity);

        CarType GetCarType(object userinfoId);

        IList<CarTypeView> GetCarTypePage(object o);
        int GetCarTypeCount(object o);
        //DataSet GetCarTypeDataSet(string queryName, object condition);
        ArrayList getCarTypeImage(CarType o);
        IList<CarTypeList> GetCarTypeList(object o);
    }
}	
	
	