// Generated by IBatisNetModel
	
using System;
using System.Collections.Generic;
using GModel.Car;

namespace GInterfaceDAL.Car
{
    public interface IFieldValuesDao
    {
        //IList<FieldValues> GetFieldValuesList(object o);
        int Update(FieldValues entity);
        int Delete(object condition);
        object Insert(FieldValues entity);

        FieldValues GetFieldValues(object userinfoId);

        IList<FieldValues> GetFieldValuesPage(object o);
        int GetFieldValuesCount(object o);
    }
}	
	
	