// Generated by IBatisNetModel
	
using System;
using System.Collections.Generic;
using GModel.Car;

namespace GInterfaceDAL.Car
{
    public interface IMonitorViewDao
    {
        MonitorView GetMonitorView(object userinfoId);
        IList<MonitorView> GetMonitorViewPage(object o);
        int GetMonitorViewCount(object o);
    }
}	
	
	