// Generated by IBatisNetModel
	
using System;
using System.Collections.Generic;
using GModel.Car;

namespace GInterfaceDAL.Car
{
    public interface IProductsInfoDao
    {
        //IList<ProductsInfo> GetProductsInfoList(object o);
        int Update(ProductsInfo entity);
        int Delete(object condition);
        object Insert(ProductsInfo entity);

        ProductsInfo GetProductsInfo(object userinfoId);

        IList<ProductsInfo> GetProductsInfoPage(object o);
        int GetProductsInfoCount(object o);
    }
}	
	
	