// Generated by IBatisNetModel
	
using System;
using System.Collections.Generic;
using GModel.Car;

namespace GInterfaceDAL.Car
{
    public interface IRailPropertyDao
    {
        //IList<RailProperty> GetRailPropertyList(object o);
        int Update(RailProperty entity);
        int Delete(object condition);
        object Insert(RailProperty entity);

        RailProperty GetRailProperty(object userinfoId);

        IList<RailProperty> GetRailPropertyPage(object o);
        int GetRailPropertyCount(object o);
    }
}	
	
	