// Generated by IBatisNetModel
	
using System;
using System.Collections.Generic;
using GModel.Car;

namespace GInterfaceDAL.Car
{
    public interface ITerminalInfoViewDao
    {
        TerminalInfoView GetTerminalInfoView(object userinfoId);
        IList<TerminalInfoView> SelectTerminalInfoViewByTerNos(object ternos);
        int SelectTerminalInfoViewByTerNosCount(object ternos);
        IList<TerminalInfoView> GetTerminalInfoViewPage(object o);
        IList<TerminalInfoView> GetNotBindTerminalInfoViewPage(object o);
        int GetTerminalInfoViewCount(object o);
        int GetNotBindTerminalInfoViewCount(object o);
    }
}	
	
	