// Generated by IBatisNetModel

using System;

using GInterfaceDAL.InterFace;
using System.Collections.Generic;
using GModel.InterFace;

namespace GDAL.InterFace
{
    public class RawDataDao : BaseSqlMapDao, IRawDataDao
    {
        public object Insert(RawData entity)
        {
            return ExecuteInsert("RawData.InsertRawData", entity);
        }

        //public int Update(RawData entity)
        //{
        //    return ExecuteUpdate("RawData.UpdateRawData", entity);
        //}

        //public int Delete(object condition)
        //{
        //    //删除跟插入调同一个方法。
        //    return ExecuteUpdate("RawData.DeleteRawData", condition);
        //}

        //RawData IRawDataDao.GetRawData(object userinfoId)
        //{
        //    return (RawData)ExecuteQueryForObject("RawData.SelectRawData", userinfoId);
        //}

        //public IList<RawData> GetRawDataPage(object o) 
        //{
        //    return ExecuteQueryForList<RawData>("RawData.SelectRawDataPage", o);
        //}

        //public int GetRawDataCount(object o) 
        //{
        //    object count = ExecuteQueryForObject("RawData.SelectRawDataCount", o);
        //    return (int)count;
        //}
    }
}
