// Generated by IBatisNetModel
	
using System;
using System.Collections.Generic;
using GModel.Location;
using System.Collections;

namespace GInterfaceDAL.Location
{
    public interface IHistoricalDataDao
    {
        //IList<HistoricalData> GetHistoricalDataList(object o);
        int Update(HistoricalData entity);
        int Delete(object condition);
        string Insert(HistoricalData entity);

        HistoricalData GetHistoricalData(object userinfoId);

        IList<HistoricalData> GetHistoricalDataPage(object o);
        int GetHistoricalDataCount(object o);
        IList<HistoricalData> GetHistorical(object ht);
        IList<TerData> GetTerHistoryData(Hashtable ht);
        int GetTerHistoryDataCount(Hashtable ht);

        IList<YXHistoricalData> GetYXHistoricalDataPage(Hashtable ht);
        int GetYXHistoricalDataCount(Hashtable ht);
    }
}	
	
	