// Generated by IBatisNetModel
	
using System;
using System.Collections.Generic;
using GModel.Location;

namespace GInterfaceDAL.Location
{
    public interface IRealtimeViewDao
    {
        RealtimeView GetRealtimeView(object userinfoId);
        IList<RealtimeView> GetRealtimeViewPage(object o);
        int GetRealtimeViewCount(object o);
    }
}	
	
	