// Generated by IBatisNetModel

using System;
using System.Collections;

using GModel.Car;
using GInterfaceDAL.Car;
using GDAL.Car;
using System.Collections.Generic;
using System.Data;

namespace GBLL.Car
{
    public class CarTypeBLL
    {
        private ICarTypeDao _iCarTypeDao = null;
        public CarTypeBLL()
        {
            _iCarTypeDao = new CarTypeDao();
        }

		public CarType GetCarType(object o)
        {
            return _iCarTypeDao.GetCarType( o);
        }

        public IList<CarTypeView> GetCarTypePage(object o)
        {
            return _iCarTypeDao.GetCarTypePage(o);
        }

        public IList<CarTypeList> GetCarTypeList(object o)
        {
            return _iCarTypeDao.GetCarTypeList(o);
        }

		public int GetCarTypeCount(object o)
        {
            return _iCarTypeDao.GetCarTypeCount(o);
        }


		public object Insert(CarType entity)
        {
            return  _iCarTypeDao.Insert(entity);
        }

        public int Update(CarType entity)
        {
            return _iCarTypeDao.Update(entity);
        }
		
        public string Delete(string condition)
        {
            return _iCarTypeDao.Delete(condition);
        }

        public ArrayList getCarTypeImage(CarType o) 
        {
            ArrayList al = _iCarTypeDao.getCarTypeImage(o);
            return al;
        }
    }
}
	