// Generated by IBatisNetModel

using System;
using System.Collections;

using GModel.Car;
using GInterfaceDAL.Car;
using GDAL.Car;
using System.Collections.Generic;

namespace GBLL.Car
{
    public class MonitorViewBLL
    {
        private IMonitorViewDao _iMonitorViewDao = null;
        public MonitorViewBLL()
        {
            _iMonitorViewDao = new MonitorViewDao();
        }

		public MonitorView GetMonitorView(object o)
        {
            return _iMonitorViewDao.GetMonitorView( o);
        }

        public IList<MonitorView> GetMonitorViewPage(object o)
        {
            return _iMonitorViewDao.GetMonitorViewPage(o);
        }

		public int GetMonitorViewCount(object o)
        {
            return _iMonitorViewDao.GetMonitorViewCount(o);
        }

        //public IList<MonitorView> GetMonitorViewList(object o)
        //{
            //return _iMonitorViewDao.GetMonitorViewList(o);
        //}
    }
}
	