// Generated by IBatisNetModel

using System;
using System.Collections;

using GModel.Car;
using GInterfaceDAL.Car;
using GDAL.Car;
using System.Collections.Generic;

namespace GBLL.Car
{
    public class ProductsInfoBLL
    {
        private IProductsInfoDao _iProductsInfoDao = null;
        public ProductsInfoBLL()
        {
            _iProductsInfoDao = new ProductsInfoDao();
        }

		public ProductsInfo GetProductsInfo(object o)
        {
            return _iProductsInfoDao.GetProductsInfo( o);
        }

        public IList<ProductsInfo> GetProductsInfoPage(object o)
        {
            return _iProductsInfoDao.GetProductsInfoPage(o);
        }

		public int GetProductsInfoCount(object o)
        {
            return _iProductsInfoDao.GetProductsInfoCount(o);
        }

        //public IList<ProductsInfo> GetProductsInfoList(object o)
        //{
            //return _iProductsInfoDao.GetProductsInfoList(o);
        //}

		public int Insert(ProductsInfo entity)
        {
            return  Convert.ToInt32(_iProductsInfoDao.Insert(entity));
        }

        public int Update(ProductsInfo entity)
        {
            return _iProductsInfoDao.Update(entity);
        }
		
        public int Delete(string condition)
        {
            return _iProductsInfoDao.Delete(condition);
        }
    }
}
	