// Generated by IBatisNetModel

using System;
using System.Collections;

using GModel.Car;
using GInterfaceDAL.Car;
using GDAL.Car;
using System.Collections.Generic;

namespace GBLL.Car
{
    public class RailPropertyBLL
    {
        private IRailPropertyDao _iRailPropertyDao = null;
        public RailPropertyBLL()
        {
            _iRailPropertyDao = new RailPropertyDao();
        }

		public RailProperty GetRailProperty(object o)
        {
            return _iRailPropertyDao.GetRailProperty( o);
        }

        public IList<RailProperty> GetRailPropertyPage(object o)
        {
            return _iRailPropertyDao.GetRailPropertyPage(o);
        }

		public int GetRailPropertyCount(object o)
        {
            return _iRailPropertyDao.GetRailPropertyCount(o);
        }

        //public IList<RailProperty> GetRailPropertyList(object o)
        //{
            //return _iRailPropertyDao.GetRailPropertyList(o);
        //}

		public int Insert(RailProperty entity)
        {
            return  Convert.ToInt32(_iRailPropertyDao.Insert(entity));
        }

        public int Update(RailProperty entity)
        {
            return _iRailPropertyDao.Update(entity);
        }
		
        public int Delete(string condition)
        {
            return _iRailPropertyDao.Delete(condition);
        }
    }
}
	