// Generated by IBatisNetModel

using System;

using GInterfaceDAL.RoleRight;
using System.Collections.Generic;
using GModel.RoleRight;

namespace GDAL.RoleRight
{
    public class MenuViewDao : BaseSqlMapDao, IMenuViewDao
    {

        MenuView IMenuViewDao.GetMenuView(object userinfoId)
        {
            return (MenuView)ExecuteQueryForObject("MenuView.SelectMenuView", userinfoId);
        }

        public IList<MenuView> GetMenuViewPage(object o) 
        {
            return ExecuteQueryForList<MenuView>("MenuView.SelectMenuViewPage", o);
        }

        public IList<MenuPower> GetMenuPower(object o) 
        {
            return ExecuteQueryForList<MenuPower>("MenuView.SelectMenuTreePower", o);
        }

		public int GetMenuViewCount(object o) 
        {
            object count = ExecuteQueryForObject("MenuView.SelectMenuViewCount", o);
            return (int)count;
        }
    }
}
	