// Generated by IBatisNetModel

using System;

using GInterfaceDAL.RoleRight;
using System.Collections.Generic;
using GModel.RoleRight;

namespace GDAL.RoleRight
{
    public class NotselMenuViewDao : BaseSqlMapDao, INotselMenuViewDao
    {

        NotselMenuView INotselMenuViewDao.GetNotselMenuView(object userinfoId)
        {
            return (NotselMenuView)ExecuteQueryForObject("NotselMenuView.SelectNotselMenuView", userinfoId);
        }

        public IList<NotselMenuView> GetNotselMenuViewPage(object o) 
        {
            return ExecuteQueryForList<NotselMenuView>("NotselMenuView.SelectNotselMenuViewPage", o);
        }

		public int GetNotselMenuViewCount(object o) 
        {
            object count = ExecuteQueryForObject("NotselMenuView.SelectNotselMenuViewCount", o);
            return (int)count;
        }
    }
}
	