// Generated by IBatisNetModel

using System;

using GInterfaceDAL.RoleRight;
using System.Collections.Generic;
using GModel.RoleRight;

namespace GDAL.RoleRight
{
    public class SelMenuViewDao : BaseSqlMapDao, ISelMenuViewDao
    {

        SelMenuView ISelMenuViewDao.GetSelMenuView(object userinfoId)
        {
            return (SelMenuView)ExecuteQueryForObject("SelMenuView.SelectSelMenuView", userinfoId);
        }

        public IList<SelMenuView> GetSelMenuViewPage(object o) 
        {
            return ExecuteQueryForList<SelMenuView>("SelMenuView.SelectSelMenuViewPage", o);
        }

		public int GetSelMenuViewCount(object o) 
        {
            object count = ExecuteQueryForObject("SelMenuView.SelectSelMenuViewCount", o);
            return (int)count;
        }
    }
}
	