// Generated by IBatisNetModel
	
using System;
using System.Collections.Generic;
using GModel.Basic;

namespace GInterfaceDAL.Basic
{
    public interface IDeptInfoDao
    {
        //IList<DeptInfo> GetDeptInfoList(object o);
        int Update(DeptInfo entity, List<string> OldDeptCode, List<string> NewDeptCode);
        int Delete(object condition);
        int DeleteChildren(object DeptId); 
        object Insert(DeptInfo entity);

        DeptInfo GetDeptInfoById(string userinfoId);

        DeptInfo GetDeptInfoByCode(string DeptCode);

        IList<DeptInfo> GetDeptInfoPage(object o);
        int GetDeptInfoCount(object o);
        int GetDeptCountByFatherId(string DeptId);
    }
}	
	
	