// Generated by IBatisNetModel

using GModel.Basic;
using System;
using System.Collections.Generic;

namespace GInterfaceDAL.Basic
{
    public interface IUserInfoDao
    {
        //IList<UserInfo> GetUserInfoList(object o);
        int Update(UserInfo entity);
        int Delete(string condition);
        int ResetUser(UserInfo userid);
        object Insert(UserInfo entity);

        UserInfo GetUserInfo(object userinfoId);

        UserInfo GetTerUserInfo(object userinfoId);

        IList<UserInfo> GetUserInfoPage(object o);
        int GetUserInfoCount(object o);

        UserInfo GetUserObjByLoginName(UserInfo ui, out UserInfo uiObj);
        int ModifyUserPWD(UserInfo ui); 
    }
}	
	
	