// Generated by IBatisNetModel
	
using System;
using System.Collections.Generic;
using GModel.Basic;

namespace GInterfaceDAL.Basic
{
    public interface IUserDeptViewDao
    {
        UserDeptView GetUserDeptView(object userinfoId);
        IList<UserDeptView> GetUserDeptViewPage(object o);
        int GetUserDeptViewCount(object o);
        IList<UserDeptView> GetTerUserViewPage(object o);
        int GetTerUserViewCount(object o);
    }
}	
	
	