// Generated by IBatisNetModel

using System;

using GInterfaceDAL.Car;
using System.Collections.Generic;
using GModel.Car;

namespace GDAL.Car
{
    public class FieldValuesDao : BaseSqlMapDao, IFieldValuesDao
    {
		 public object Insert(FieldValues entity)
        {
            return ExecuteInsert("FieldValues.InsertFieldValues", entity);
        }

        public int Update(FieldValues entity)
        {
            return ExecuteUpdate("FieldValues.UpdateFieldValues", entity);
        }

		public int Delete(object condition)
        {
            //删除跟插入调同一个方法。
            return ExecuteUpdate("FieldValues.DeleteFieldValues", condition);
        }

        FieldValues IFieldValuesDao.GetFieldValues(object userinfoId)
        {
            return (FieldValues)ExecuteQueryForObject("FieldValues.SelectFieldValues", userinfoId);
        }

		//public IList<FieldValues> GetFieldValuesList(object o)
        //{
            //return ExecuteQueryForList<FieldValues>("FieldValues.SelectFieldValues", o);  
        //}

        public IList<FieldValues> GetFieldValuesPage(object o) 
        {
            return ExecuteQueryForList<FieldValues>("FieldValues.SelectFieldValuesPage", o);
        }

		public int GetFieldValuesCount(object o) 
        {
            object count = ExecuteQueryForObject("FieldValues.SelectFieldValuesCount", o);
            return (int)count;
        }
    }
}
	