// Generated by IBatisNetModel

using System;

using GInterfaceDAL.Car;
using System.Collections.Generic;
using GModel.Car;

namespace GDAL.Car
{
    public class ProductsInfoDao : BaseSqlMapDao, IProductsInfoDao
    {
		 public object Insert(ProductsInfo entity)
        {
            return ExecuteInsert("ProductsInfo.InsertProductsInfo", entity);
        }

        public int Update(ProductsInfo entity)
        {
            return ExecuteUpdate("ProductsInfo.UpdateProductsInfo", entity);
        }

		public int Delete(object condition)
        {
            //删除跟插入调同一个方法。
            return ExecuteUpdate("ProductsInfo.DeleteProductsInfo", condition);
        }

        ProductsInfo IProductsInfoDao.GetProductsInfo(object userinfoId)
        {
            return (ProductsInfo)ExecuteQueryForObject("ProductsInfo.SelectProductsInfo", userinfoId);
        }

		//public IList<ProductsInfo> GetProductsInfoList(object o)
        //{
            //return ExecuteQueryForList<ProductsInfo>("ProductsInfo.SelectProductsInfo", o);  
        //}

        public IList<ProductsInfo> GetProductsInfoPage(object o) 
        {
            return ExecuteQueryForList<ProductsInfo>("ProductsInfo.SelectProductsInfoPage", o);
        }

		public int GetProductsInfoCount(object o) 
        {
            object count = ExecuteQueryForObject("ProductsInfo.SelectProductsInfoCount", o);
            return (int)count;
        }
    }
}
	