// Generated by IBatisNetModel

using System;

using GInterfaceDAL.Car;
using System.Collections.Generic;
using GModel.Car;

namespace GDAL.Car
{
    public class RailPropertyDao : BaseSqlMapDao, IRailPropertyDao
    {
		 public object Insert(RailProperty entity)
        {
            return ExecuteInsert("RailProperty.InsertRailProperty", entity);
        }

        public int Update(RailProperty entity)
        {
            return ExecuteUpdate("RailProperty.UpdateRailProperty", entity);
        }

		public int Delete(object condition)
        {
            //删除跟插入调同一个方法。
            return ExecuteUpdate("RailProperty.DeleteRailProperty", condition);
        }

        RailProperty IRailPropertyDao.GetRailProperty(object userinfoId)
        {
            return (RailProperty)ExecuteQueryForObject("RailProperty.SelectRailProperty", userinfoId);
        }

		//public IList<RailProperty> GetRailPropertyList(object o)
        //{
            //return ExecuteQueryForList<RailProperty>("RailProperty.SelectRailProperty", o);  
        //}

        public IList<RailProperty> GetRailPropertyPage(object o) 
        {
            return ExecuteQueryForList<RailProperty>("RailProperty.SelectRailPropertyPage", o);
        }

		public int GetRailPropertyCount(object o) 
        {
            object count = ExecuteQueryForObject("RailProperty.SelectRailPropertyCount", o);
            return (int)count;
        }
    }
}
	