// Generated by IBatisNetModel

using System;

using GInterfaceDAL.Basic;
using System.Collections.Generic;
using GModel.Basic;
using IBatisNet.DataMapper;

namespace GDAL.Basic
{
    public class VersionInfoDao : BaseSqlMapDao, IVersionInfoDao
    {
        public IList<VersionInfo> GetVersionViewPage(object o)
        {
            return ExecuteQueryForList<VersionInfo>("VersionInfo.SelectVerInfoPage", o);
        }

        public int GetVersionViewCount(object o)
        {
            object count = ExecuteQueryForObject("VersionInfo.SelectVerInfoCount", o);
            return (int)count;
        }

        public object Insert(VersionInfo entity)
        {
            return ExecuteInsert("VersionInfo.InsertVersionInfo", entity);
        }

        public int Update(VersionInfo entity)
        {
            return ExecuteUpdate("VersionInfo.UpdateVersionInfo", entity);
        }

        public int Delete(object condition)
        {
            //删除跟插入调同一个方法。
            return ExecuteUpdate("VersionInfo.DeleteVersionInfo", condition);
        }

        public VersionInfo GetVersionInfo(VersionInfo vi)
        {
            return (VersionInfo)ExecuteQueryForObject("VersionInfo.SelectMenuInfo", vi);
        }
    }
}
	