// Generated by IBatisNetModel

using System;
using System.Collections;

using GModel.Location;
using GInterfaceDAL.Location;
using GDAL.Location;
using System.Collections.Generic;

namespace GBLL.Location
{
    public class RealtimeViewBLL
    {
        private IRealtimeViewDao _iRealtimeViewDao = null;
        public RealtimeViewBLL()
        {
            _iRealtimeViewDao = new RealtimeViewDao();
        }

		public RealtimeView GetRealtimeView(object o)
        {
            return _iRealtimeViewDao.GetRealtimeView( o);
        }

        public IList<RealtimeView> GetRealtimeViewPage(object o)
        {
            return _iRealtimeViewDao.GetRealtimeViewPage(o);
        }

		public int GetRealtimeViewCount(object o)
        {
            return _iRealtimeViewDao.GetRealtimeViewCount(o);
        }
    }
}
	