// Generated by IBatisNetModel
using System;

namespace GModel.Car
{
	[Serializable]
	public class CarTypeList
	{
		#region Private Members
		private bool _isChanged;
		private bool _isDeleted;
		private int _startdata=0;
        private int _enddata=0;
		private int _newRow = 0;
		
		private string _type_id; 
		private string _type_name; 
		private string _businessdivisioncode; 	
	    
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public CarTypeList()
		{
			_type_id = ""; 
			_type_name = ""; 
			_businessdivisioncode = ""; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public string TypeId
		{
			get { return _type_id; }
			set	
			{
				if( value!= null && value.Length > 40)
					throw new ArgumentOutOfRangeException("Invalid value for TypeId", value, value.ToString());
				
				_isChanged |= (_type_id != value); _type_id = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string TypeName
		{
			get { return _type_name; }
			set	
			{
				if( value!= null && value.Length > 202)
					throw new ArgumentOutOfRangeException("Invalid value for TypeName", value, value.ToString());
				
				_isChanged |= (_type_name != value); _type_name = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string Businessdivisioncode
		{
			get { return _businessdivisioncode; }
			set	
			{
                //if( value!= null && value.Length > 80)
                //    throw new ArgumentOutOfRangeException("Invalid value for Businessdivisioncode", value, value.ToString());
				
				_isChanged |= (_businessdivisioncode != value); _businessdivisioncode = value;
			}
		}

        public string Businessdivisionid
        {
            get;
            set;
        }
			
		
		public int StartData
        {
            get { return _startdata;}
            set
            {
                _startdata = value;
            }
        }
		
        public int EndData
        {
            get { return _enddata; }
            set	
            {
                 _enddata = value;
            }
        }
		public int NewRow 
        {
            get { return _newRow; }
            set { _newRow = value; }
        }
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		
	}
}
