// Generated by IBatisNetModel
using System;

namespace GModel.Car
{
	[Serializable]
	public class MonitorView
	{
		#region Private Members
		private bool _isChanged;
		private bool _isDeleted;
		private int _startdata=0;
        private int _enddata=0;
		private int _newRow = 0;
		
		private double _baidu_latitude; 
		private double _baidu_longitude; 
		private double _google_latitude; 
		private double _google_longitude; 
		private string _ter_guid; 
		private string _car_no; 
		private string _car_id; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public MonitorView()
		{
			_baidu_latitude = new double(); 
			_baidu_longitude = new double(); 
			_google_latitude = new double(); 
			_google_longitude = new double(); 
			_ter_guid = ""; 
			_car_no = ""; 
			_car_id = ""; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public double BaiduLatitude
		{
			get { return _baidu_latitude; }
			set { _isChanged |= (_baidu_latitude != value); _baidu_latitude = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public double BaiduLongitude
		{
			get { return _baidu_longitude; }
			set { _isChanged |= (_baidu_longitude != value); _baidu_longitude = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public double GoogleLatitude
		{
			get { return _google_latitude; }
			set { _isChanged |= (_google_latitude != value); _google_latitude = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public double GoogleLongitude
		{
			get { return _google_longitude; }
			set { _isChanged |= (_google_longitude != value); _google_longitude = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string TerGuid
		{
			get { return _ter_guid; }
			set	
			{
				if( value!= null && value.Length > 40)
					throw new ArgumentOutOfRangeException("Invalid value for TerGuid", value, value.ToString());
				
				_isChanged |= (_ter_guid != value); _ter_guid = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string CarNo
		{
			get { return _car_no; }
			set	
			{
				if( value!= null && value.Length > 40)
					throw new ArgumentOutOfRangeException("Invalid value for CarNo", value, value.ToString());
				
				_isChanged |= (_car_no != value); _car_no = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string CarId
		{
			get { return _car_id; }
			set	
			{
				if( value!= null && value.Length > 40)
					throw new ArgumentOutOfRangeException("Invalid value for CarId", value, value.ToString());
				
				_isChanged |= (_car_id != value); _car_id = value;
			}
		}
			
		
		public int StartData
        {
            get { return _startdata;}
            set
            {
                _startdata = value;
            }
        }
		
        public int EndData
        {
            get { return _enddata; }
            set	
            {
                 _enddata = value;
            }
        }
		public int NewRow 
        {
            get { return _newRow; }
            set { _newRow = value; }
        }
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		
	}
}
