// Generated by IBatisNetModel
using System;

namespace GModel.Car
{
	[Serializable]
	public class RegistrationInfo
	{
		#region Private Members
		private bool _isChanged;
		private bool _isDeleted;
		private int _startdata=0;
        private int _enddata=0;
		private int _newRow = 0;
		
		private string _reg_id; 
		private string _reg_owner; 
		private string _owner_address; 
		private string _use_properties; 
		private string _car_model; 
		private string _vehicle_code; 
		private string _modified_model; 
		private DateTime _reg_date; 
		private string _car_no; 
		private DateTime _issue_date; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public RegistrationInfo()
		{
			_reg_id = ""; 
			_reg_owner = ""; 
			_owner_address = ""; 
			_use_properties = ""; 
			_car_model = ""; 
			_vehicle_code = ""; 
			_modified_model = ""; 
			_reg_date = new DateTime(); 
			_car_no = ""; 
			_issue_date = new DateTime(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// ID
		/// </summary>		
		public string RegId
		{
			get { return _reg_id; }
			set	
			{
				if( value!= null && value.Length > 40)
					throw new ArgumentOutOfRangeException("Invalid value for RegId", value, value.ToString());
				
				_isChanged |= (_reg_id != value); _reg_id = value;
			}
		}
			
		/// <summary>
		/// 所有人
		/// </summary>		
		public string RegOwner
		{
			get { return _reg_owner; }
			set	
			{
				if( value!= null && value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for RegOwner", value, value.ToString());
				
				_isChanged |= (_reg_owner != value); _reg_owner = value;
			}
		}
			
		/// <summary>
		/// 地址
		/// </summary>		
		public string OwnerAddress
		{
			get { return _owner_address; }
			set	
			{
				if( value!= null && value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for OwnerAddress", value, value.ToString());
				
				_isChanged |= (_owner_address != value); _owner_address = value;
			}
		}
			
		/// <summary>
		/// 使用性质
		/// </summary>		
		public string UseProperties
		{
			get { return _use_properties; }
			set	
			{
				if( value!= null && value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for UseProperties", value, value.ToString());
				
				_isChanged |= (_use_properties != value); _use_properties = value;
			}
		}
			
		/// <summary>
		/// 车辆类型
		/// </summary>		
		public string CarModel
		{
			get { return _car_model; }
			set	
			{
				if( value!= null && value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for CarModel", value, value.ToString());
				
				_isChanged |= (_car_model != value); _car_model = value;
			}
		}
			
		/// <summary>
		/// 车辆识别代号
		/// </summary>		
		public string VehicleCode
		{
			get { return _vehicle_code; }
			set	
			{
				if( value!= null && value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for VehicleCode", value, value.ToString());
				
				_isChanged |= (_vehicle_code != value); _vehicle_code = value;
			}
		}
			
		/// <summary>
		/// 改动机型号
		/// </summary>		
		public string ModifiedModel
		{
			get { return _modified_model; }
			set	
			{
				if( value!= null && value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for ModifiedModel", value, value.ToString());
				
				_isChanged |= (_modified_model != value); _modified_model = value;
			}
		}
			
		/// <summary>
		/// 注册日期
		/// </summary>		
		public DateTime RegDate
		{
			get { return _reg_date; }
			set { _isChanged |= (_reg_date != value); _reg_date = value; }
		}
			
		/// <summary>
		/// 车牌号
		/// </summary>		
		public string CarNo
		{
			get { return _car_no; }
			set	
			{
				if( value!= null && value.Length > 20)
					throw new ArgumentOutOfRangeException("Invalid value for CarNo", value, value.ToString());
				
				_isChanged |= (_car_no != value); _car_no = value;
			}
		}
			
		/// <summary>
		/// 发证日期
		/// </summary>		
		public DateTime IssueDate
		{
			get { return _issue_date; }
			set { _isChanged |= (_issue_date != value); _issue_date = value; }
		}
			
		
		public int StartData
        {
            get { return _startdata;}
            set
            {
                _startdata = value;
            }
        }
		
        public int EndData
        {
            get { return _enddata; }
            set	
            {
                 _enddata = value;
            }
        }
		public int NewRow 
        {
            get { return _newRow; }
            set { _newRow = value; }
        }
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return _isChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return _isDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			_isDeleted = true;
			_isChanged = true;
		}
		
		#endregion
		
		
	}
}
